# Generated by Django 5.2.2 on 2025-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mob', models.IntegerField()),
                ('gender', models.CharField()),
                ('pwd', models.CharField()),
            ],
        ),
    ]
