# Generated by Django 5.2.4 on 2025-07-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5)),
                ('image', models.ImageField(default='Image/free.png', upload_to='Image/')),
                ('pwd', models.CharField(max_length=128)),
            ],
        ),
    ]
