# Generated by Django 5.2.4 on 2025-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_id_user_userid_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
