# Generated by Django 5.2.4 on 2025-07-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Blog',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authorName', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='BlogImage/')),
                ('desctitle', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
