# Generated by Django 5.2.4 on 2025-07-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_blog',
            old_name='dob',
            new_name='date',
        ),
    ]
