# Generated by Django 5.2.4 on 2025-07-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_dob_add_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_blog',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
