# Generated by Django 5.2.4 on 2025-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_add_blog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_blog',
            name='authorName',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='add_blog',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_blog',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='add_blog',
            name='desctitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='add_blog',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
